import pygame


CELL_SIZE = 30
COUNT_CELLS_WIDTH = 10
COUNT_CELLS_HEIGHT = 10
MAX_SCORE = COUNT_CELLS_WIDTH * COUNT_CELLS_HEIGHT
SCREEN_WIDTH = CELL_SIZE * COUNT_CELLS_WIDTH
SCREEN_HEIGHT = CELL_SIZE * COUNT_CELLS_HEIGHT
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
TICK_DELAY = 200

# Colors
SNAKE_COLOR = pygame.Color(0, 255, 0)
APPLE_COLOR = pygame.Color(255, 0, 0)
BG_COLOR = pygame.Color(0, 0, 0)

# Font
FONT_PATH = 'game/fonts/Roboto-Regular.ttf'
FONT_SIZE = 24
FONT_COLOR = pygame.Color(255, 255, 255)
